@host= http://localhost:8000/v1/user

# ---------------------------------------------------------------------------
### User SIGN_UP endpoint
# ---------------------------------------------------------------------------
POST {{host}} HTTP/1.1
Content-Type: application/json

{
  "name":"kannada",
  "company":"company name",
  "address":"somwhere in bangalore",
  "phone":494561649162,
  "email":"india@india.com",
  "password":"india123"
}

# ---------------------------------------------------------------------------
### User SIGN-IN endpoint
# ---------------------------------------------------------------------------
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "email":"india@india.com",
  "password":"india123"
}

# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------